# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: b99d84d8842ba45ef3729ba0695500e170113d2deec2d8f159c4e8451e9798775acda91d96b97fffd7a08f8cccb3f87646be4526eb0df41e3002cf6743bb4312

test:
  secret_key_base: 1ee6667325778a68b9a120326b3d4dc5f223e32d309228e65354ffa5fd32dc0ded9fd4656dc21fcb149a32ae197b11fd68d0102182031c5a5ac0c02b0d0bbe25

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
